apiVersion: v1
kind: Service
metadata:
    name: "azk8s-95e5"
    labels:
        app: "azk8s-95e5"
spec:
    type: LoadBalancer
    ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
    selector:
        app: "azk8s-95e5"