on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n azk8sapps -g azk8sapps8026-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n azk8sapps --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n azk8sapps --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n azk8sapps --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: azk8sapps.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/projects/rrshare" -f  "projects/rrshare/Dockerfile" -t azk8sapps.azurecr.io/azk8s:${{ github.sha }} --label dockerfile-path=projects/rrshare/Dockerfile
        docker push azk8sapps.azurecr.io/azk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_azk8s_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rrweb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rrweb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rrweb
        container-registry-url: azk8sapps.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: azk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rrweb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azk8sapps.azurecr.io/azk8s:${{ github.sha }}
        imagepullsecrets: |
          azk8sdockerauth   
